[package]
name = "data_importer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[[bin]]
name = "main"
path = "src/main.rs"


[dependencies.common]
path = "../../flv_common"
version = "0.1.0"


[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
questdb-rs = { workspace = true }
