[package]
name = "client_login_errors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[[bin]]
name = "client_login_errors"
path = "src/bin/main.rs"


[lib]
name = "lib_client_login_errors"
path = "src/lib/mod.rs"


[dependencies]
# Internal crates
common = { workspace = true }
sbe_messages = { workspace = true }
# External crates
futures = { workspace = true }
tokio = { workspace = true }
fluvio = { workspace = true }