[package]
name = "exchange_specs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[lib]
name = "exchange_specs"
path = "src/lib.rs"


[dependencies]
# Internal crates
common = {workspace = true}
