[package]
name = "sbe_bindings"
version = "0.1.0"
authors = ["sbetool"]
description = "Fluvio DeepCausality Schema"
edition = "2021"

[lib]
name = "sbe_bindings"
path = "src/lib.rs"
[dependencies]
serde = { version = "1.0.195", features = ["derive"] }